### ISSUE TITLE
illegal instruction?

### ISSUE THREAD

**Issue by lopusz** [conda-forge/spacy-feedstock#24]
Dear SpaCy Team,

first of all thank you for the amazing library :) Great work!

I have a strange issue trying to install spaCy 2.0.2 from conda-forge.
My google foo is too weak to locate something meaningful :(
Perhaps you have an idea what is going wrong?

While running a simple script for NER I get an error.
```
Illegal instruction     (core dumped) python ner.py
```
The reproducing script installing spaCy and running the example is attached. I believe it might have something to do with the instructions supported by my (not so new) CPU, so I include snippet from my cpuinfo:

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz
...
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer xsave avx f16c rdrand lahf_lm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt
```
I am on Ubuntu 14.04.

I tried on another machine (also with not brand new CPU) and it behaves similarly.

Perhaps I missed something basic?

Thank you in advance for any of your hints.

Best regards,
Michał

[install_and_run.txt](https://github.com/conda-forge/spacy-feedstock/files/1478804/install_and_run.txt)

**Comment by rmax** [comment]
Hi, thanks for the report!

For reference, this is the feedstock build log: https://circleci.com/gh/conda-forge/spacy-feedstock/81

Maybe it's related to the `-march=native` flag. From my little search, it seems the flags for a portable build are `-march=x86-64 -mtune=generic`.

The question is where the fix should go, either spacy's `setup.py` or a recipe patch.

@jakirkham @honnibal any thoughts?

**Comment by rmax** [comment]
@lopusz Could you confirm if the release 2.0.3 fixes your issue?

**Comment by jakirkham** [comment]
Sorry. Just now saw this.

Yeah `-march=native` is probably a bad idea. The CIs may not be on the latest and greatest architecture, but they may be more advanced then most machines. So would not be surprised if it ran unsupported instructions.

Typically one wants `-march=<something really old>` and `-mtune=generic`. Our plan with the new compilers is similar. We picked `-march=nocona`, which is more than a decade old (should be safe). Though it seems we didn't choose `-mtune=generic`, which I'm following up on.

ref: https://paper.dropbox.com/doc/Compiler-meeting-20171116-1lYaDIP93JRzzQZBlicxg

**Comment by lopusz** [comment]
Dear SpaCy Team, Dear @rmax,

I am sorry for being a bit unresponsive :( 

Spacy 2.0.4 works fine on both machines I tested. Thank you for the fix!

I do not know how about comment of @jakirkham. So I am not closing the issue.
However, for me it is solved.

Best regards,
Michał
