### ISSUE TITLE
Unable to install "spacy 2.3.2" with "cython-blis 0.7.1"

### ISSUE THREAD

**Issue by rhazegh** [conda-forge/spacy-feedstock#85]
The following fails:
```
conda install --quiet --yes \
    'cython-blis=0.7.1' \
    'spacy=2.3.2'
```

with this error message:
```
Package cython-blis conflicts for:
cython-blis=0.7.1
spacy=2.3.2 -> cython-blis[version='>=0.4.0,<0.5.0']
```

It seems it currently needs cython-blis < 0.5.0. Changing this to a larger version number should fix the issue.

See  https://github.com/explosion/cython-blis/issues/29 and https://github.com/conda-forge/cython-blis-feedstock/issues/18  for context.

**Comment by rmax** [comment]
Need to wait for upstream update https://github.com/explosion/spaCy/blob/master/setup.cfg#L48

**Comment by rhazegh** [comment]
@rmax Is there an issue in spaCy repo to ensure this will be done for the next major/minor release? Any idea when that would happen? Thanks.

**Comment by rmax** [comment]
@rhazegh I see that the dependency update PR was just merged https://github.com/explosion/spaCy/pull/6198

@ines or @adrianeboyd may be able to comment more on the release schedule.

**Comment by adrianeboyd** [comment]
There are difficulties with older versions of `pip` (not conda) and the binary wheels for `blis`, which is why we've been delaying on this upgrade a little. It's definitely planned for spacy v3 (in the PR linked above), but I'm not currently sure whether the next patch release for spacy v2.3 will include this change.

**Comment by adrianeboyd** [comment]
spacy v2.3.3 (coming very soon) will support blis `>=0.4.0,<0.8.0`.
