### ISSUE TITLE
Many travis/drone builds of 3.0 failed

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/spacy-feedstock#96]
Thanks for maintaining this!

Looks like at least [some of the builds](https://cloud.drone.io/conda-forge/spacy-feedstock/24/1/2) on #95 (and the subsequent merge) went :boom: because of a missing `pathy`. This might help:

- https://github.com/conda-forge/pathy-feedstock/pull/4

If that gets merged (looks like there's some overlap between maintainers), then those jobs _might_ be restartable to get the builds uploaded...

**Comment by adrianeboyd** [comment]
It's mostly working at this point for v3.0.1, which should be available in the next 1-2 hours. (Hopefully there aren't a lot of ppc64le python3.6 users?)
